-- First delete existing products to prevent duplicates (handles unique conflicts manually)
DELETE FROM public.products WHERE handle IN (
  'cp-plus-2-4-mp-4-camera-setup',
  'cp-plus-2-4-mp-8-camera-setup',
  'cp-plus-5-mp-4-camera-setup',
  'cp-plus-5-mp-8-camera-setup',
  'cp-plus-2mp-ip-16-camera-setup',
  'cp-plus-2mp-ip-8-camera-setup',
  'cp-plus-2mp-ip-4-camera-setup',
  'cp-plus-4mp-ip-16-camera-setup',
  'cp-plus-4mp-ip-8-camera-setup',
  'cp-plus-4mp-ip-4-camera-setup',
  'seagate-1-tb-hdd-surveillance',
  'seagate-2tb-hdd-surveillance',
  'consistent-500gb-hdd',
  'consistent-1tb-hdd'
);

-- SQL to insert the new products and mark them as active (latest)
INSERT INTO public.products (
  handle,
  name,
  title,
  description,
  brand,
  price,
  mrp,
  stock_status,
  status,
  warranty,
  category,
  image,
  images,
  created_at
) VALUES 
(
  'cp-plus-2-4-mp-4-camera-setup',
  'CP PLUS 2.4 MP - 4 Camera Full Setup 2Dom and 2Bullet Analogue Dual Light cameras',
  'CP PLUS 2.4 MP - 4 Camera Full Setup 2Dom and 2Bullet Analogue Dual Light cameras',
  'CP PLUS 2.4 MP - 4 Camera Full Setup containing 2 Dome and 2 Bullet Analogue Dual Light cameras. Complete set without hard drive. Includes DVR 8CH, 10amps SMPS, 4 Cameras, and 100Mtr CCTV wire.',
  'CP PLUS',
  17999.00,
  24999.00,
  'in_stock',
  'active'::product_lifecycle_status,
  '1 Year',
  'CCTV Setup',
  'https://fbcsagupcxheyiusjfak.supabase.co/storage/v1/object/public/images/products/placeholder-cctv.webp',
  ARRAY['https://fbcsagupcxheyiusjfak.supabase.co/storage/v1/object/public/images/products/placeholder-cctv.webp'],
  NOW()
),
(
  'cp-plus-2-4-mp-8-camera-setup',
  'CP PLUS 2.4 MP - 8 Camera Full Setup 4Dom and 4Bullet Analogue Dual Light cameras',
  'CP PLUS 2.4 MP - 8 Camera Full Setup 4Dom and 4Bullet Analogue Dual Light cameras',
  'CP PLUS 2.4 MP - 8 Camera Full Setup containing 4 Dome and 4 Bullet Analogue Dual Light cameras. Complete set without hard drive. Includes DVR 8CH, 10amps SMPS, 8 Cameras, and 100Mtr CCTV wire.',
  'CP PLUS',
  25999.00,
  33999.00,
  'in_stock',
  'active'::product_lifecycle_status,
  '1 Year',
  'CCTV Setup',
  'https://fbcsagupcxheyiusjfak.supabase.co/storage/v1/object/public/images/products/placeholder-cctv.webp',
  ARRAY['https://fbcsagupcxheyiusjfak.supabase.co/storage/v1/object/public/images/products/placeholder-cctv.webp'],
  NOW()
),
(
  'cp-plus-5-mp-4-camera-setup',
  'CP PLUS 5 MP - 4 Camera Full Setup 2Dom and 2Bullet Analogue Dual Light cameras',
  'CP PLUS 5 MP - 4 Camera Full Setup 2Dom and 2Bullet Analogue Dual Light cameras',
  'CP PLUS 5 MP - 4 Camera Full Setup containing 2 Dome and 2 Bullet Analogue Dual Light cameras. Complete set without hard drive. Includes DVR 8CH, 10amps SMPS, 4 Cameras, and 100Mtr CCTV wire.',
  'CP PLUS',
  23999.00,
  31999.00,
  'in_stock',
  'active'::product_lifecycle_status,
  '1 Year',
  'CCTV Setup',
  'https://fbcsagupcxheyiusjfak.supabase.co/storage/v1/object/public/images/products/placeholder-cctv.webp',
  ARRAY['https://fbcsagupcxheyiusjfak.supabase.co/storage/v1/object/public/images/products/placeholder-cctv.webp'],
  NOW()
),
(
  'cp-plus-5-mp-8-camera-setup',
  'CP PLUS 5 MP - 8 Camera Full Setup 4Dom and 4Bullet Analogue Dual Light cameras',
  'CP PLUS 5 MP - 8 Camera Full Setup 4Dom and 4Bullet Analogue Dual Light cameras',
  'CP PLUS 5 MP - 8 Camera Full Setup containing 4 Dome and 4 Bullet Analogue Dual Light cameras. Complete set without hard drive. Includes DVR 8CH, 10amps SMPS, 8 Cameras, and 100Mtr CCTV wire.',
  'CP PLUS',
  33999.00,
  37999.00,
  'in_stock',
  'active'::product_lifecycle_status,
  '1 Year',
  'CCTV Setup',
  'https://fbcsagupcxheyiusjfak.supabase.co/storage/v1/object/public/images/products/placeholder-cctv.webp',
  ARRAY['https://fbcsagupcxheyiusjfak.supabase.co/storage/v1/object/public/images/products/placeholder-cctv.webp'],
  NOW()
),
(
  'cp-plus-2mp-ip-16-camera-setup',
  'CP PLUS 2MP IP 16 Camera Full Setup 4Dom and 12Bullet IP Dual Light cameras',
  'CP PLUS 2MP IP 16 Camera Full Setup 4Dom and 12Bullet IP Dual Light cameras',
  'CP PLUS 2MP IP 16 Camera Full Setup containing 4 Dome and 12 Bullet IP Dual Light cameras. Complete set without hard drive. Includes NVR 16CH, 2pcs POE 8CH, 16 Cameras, and 100Mtr Lan Cable.',
  'CP PLUS',
  81999.00,
  129999.00,
  'in_stock',
  'active'::product_lifecycle_status,
  '1 Year',
  'CCTV Setup',
  'https://fbcsagupcxheyiusjfak.supabase.co/storage/v1/object/public/images/products/placeholder-cctv.webp',
  ARRAY['https://fbcsagupcxheyiusjfak.supabase.co/storage/v1/object/public/images/products/placeholder-cctv.webp'],
  NOW()
),
(
  'cp-plus-2mp-ip-8-camera-setup',
  'CP PLUS 2MP IP 8 Camera Full Setup 4Dom and 4Bullet IP Dual Light cameras',
  'CP PLUS 2MP IP 8 Camera Full Setup 4Dom and 4Bullet IP Dual Light cameras',
  'CP PLUS 2MP IP 8 Camera Full Setup containing 4 Dome and 4 Bullet IP Dual Light cameras. Complete set without hard drive. Includes NVR 8CH, 1pc POE 8CH, 8 Cameras, and 100Mtr Lan Cable.',
  'CP PLUS',
  49999.00,
  75999.00,
  'in_stock',
  'active'::product_lifecycle_status,
  '1 Year',
  'CCTV Setup',
  'https://fbcsagupcxheyiusjfak.supabase.co/storage/v1/object/public/images/products/placeholder-cctv.webp',
  ARRAY['https://fbcsagupcxheyiusjfak.supabase.co/storage/v1/object/public/images/products/placeholder-cctv.webp'],
  NOW()
),
(
  'cp-plus-2mp-ip-4-camera-setup',
  'CP PLUS 2MP IP 4 Camera Full Setup 4Dom and 4Bullet IP Dual Light cameras',
  'CP PLUS 2MP IP 4 Camera Full Setup 4Dom and 4Bullet IP Dual Light cameras',
  'CP PLUS 2MP IP 4 Camera Full Setup containing 4 Dome and 4 Bullet IP Dual Light cameras. Complete set without hard drive. Includes NVR 8CH, 1pc POE 8CH, 4 Cameras, and 100Mtr Lan Cable.',
  'CP PLUS',
  29999.00,
  47999.00,
  'in_stock',
  'active'::product_lifecycle_status,
  '1 Year',
  'CCTV Setup',
  'https://fbcsagupcxheyiusjfak.supabase.co/storage/v1/object/public/images/products/placeholder-cctv.webp',
  ARRAY['https://fbcsagupcxheyiusjfak.supabase.co/storage/v1/object/public/images/products/placeholder-cctv.webp'],
  NOW()
),
(
  'cp-plus-4mp-ip-16-camera-setup',
  'CP PLUS 4MP IP 16 Camera Full Setup 4Dom and 12Bullet IP Dual Light cameras',
  'CP PLUS 4MP IP 16 Camera Full Setup 4Dom and 12Bullet IP Dual Light cameras',
  'CP PLUS 4MP IP 16 Camera Full Setup containing 4 Dome and 12 Bullet IP Dual Light cameras. Complete set without hard drive. Includes NVR 16CH, 2pcs POE 8CH, 16 Cameras, and 100Mtr CCTV wire.',
  'CP PLUS',
  99999.00,
  145999.00,
  'in_stock',
  'active'::product_lifecycle_status,
  '1 Year',
  'CCTV Setup',
  'https://fbcsagupcxheyiusjfak.supabase.co/storage/v1/object/public/images/products/placeholder-cctv.webp',
  ARRAY['https://fbcsagupcxheyiusjfak.supabase.co/storage/v1/object/public/images/products/placeholder-cctv.webp'],
  NOW()
),
(
  'cp-plus-4mp-ip-8-camera-setup',
  'CP PLUS 4MP IP 8 Camera Full Setup 4Dom and 4Bullet IP Dual Light cameras',
  'CP PLUS 4MP IP 8 Camera Full Setup 4Dom and 4Bullet IP Dual Light cameras',
  'CP PLUS 4MP IP 8 Camera Full Setup containing 4 Dome and 4 Bullet IP Dual Light cameras. Complete set without hard drive. Includes NVR 16CH, 1pc POE 8CH, 8 Cameras, and 100Mtr CCTV wire.',
  'CP PLUS',
  75999.00,
  95999.00,
  'in_stock',
  'active'::product_lifecycle_status,
  '1 Year',
  'CCTV Setup',
  'https://fbcsagupcxheyiusjfak.supabase.co/storage/v1/object/public/images/products/placeholder-cctv.webp',
  ARRAY['https://fbcsagupcxheyiusjfak.supabase.co/storage/v1/object/public/images/products/placeholder-cctv.webp'],
  NOW()
),
(
  'cp-plus-4mp-ip-4-camera-setup',
  'CP PLUS 4MP IP 4 Camera Full Setup 4Dom and 4Bullet IP Dual Light cameras',
  'CP PLUS 4MP IP 4 Camera Full Setup 4Dom and 4Bullet IP Dual Light cameras',
  'CP PLUS 4MP IP 4 Camera Full Setup containing 4 Dome and 4 Bullet IP Dual Light cameras. Complete set without hard drive. Includes NVR 16CH, 1pc POE 8CH, 4 Cameras, and 100Mtr CCTV wire.',
  'CP PLUS',
  39999.00,
  145999.00,
  'in_stock',
  'active'::product_lifecycle_status,
  '1 Year',
  'CCTV Setup',
  'https://fbcsagupcxheyiusjfak.supabase.co/storage/v1/object/public/images/products/placeholder-cctv.webp',
  ARRAY['https://fbcsagupcxheyiusjfak.supabase.co/storage/v1/object/public/images/products/placeholder-cctv.webp'],
  NOW()
),
(
  'seagate-1-tb-hdd-surveillance',
  'Seagate 1 TB HDD Surveillance',
  'Seagate 1 TB HDD Surveillance',
  'Seagate Surveillance HDD 1 TB storage drive built for 24/7 video capture systems. Offers high performance and reliability for multiple security camera feeds.',
  'Seagate',
  11999.00,
  14999.00,
  'in_stock',
  'active'::product_lifecycle_status,
  '3 Years',
  'Storage',
  'https://fbcsagupcxheyiusjfak.supabase.co/storage/v1/object/public/images/products/placeholder-storage.webp',
  ARRAY['https://fbcsagupcxheyiusjfak.supabase.co/storage/v1/object/public/images/products/placeholder-storage.webp'],
  NOW()
),
(
  'seagate-2tb-hdd-surveillance',
  'Seagate 2TB HDD Surveillance',
  'Seagate 2TB HDD Surveillance',
  'Seagate Surveillance HDD 2 TB storage drive built for 24/7 video capture systems. Provides expanded capacity for longer video archive retention.',
  'Seagate',
  13999.00,
  17999.00,
  'in_stock',
  'active'::product_lifecycle_status,
  '3 Years',
  'Storage',
  'https://fbcsagupcxheyiusjfak.supabase.co/storage/v1/object/public/images/products/placeholder-storage.webp',
  ARRAY['https://fbcsagupcxheyiusjfak.supabase.co/storage/v1/object/public/images/products/placeholder-storage.webp'],
  NOW()
),
(
  'consistent-500gb-hdd',
  'Consistant 500GB HDD',
  'Consistant 500GB HDD',
  'Consistant 500 GB Hard Disk Drive for surveillance and desktop computer storage. Reliable budget storage solution.',
  'Consistent',
  5999.00,
  7999.00,
  'in_stock',
  'active'::product_lifecycle_status,
  '2 Years',
  'Storage',
  'https://fbcsagupcxheyiusjfak.supabase.co/storage/v1/object/public/images/products/placeholder-storage.webp',
  ARRAY['https://fbcsagupcxheyiusjfak.supabase.co/storage/v1/object/public/images/products/placeholder-storage.webp'],
  NOW()
),
(
  'consistent-1tb-hdd',
  'Consistant 1TB HDD',
  'Consistant 1TB HDD',
  'Consistant 1 TB Hard Disk Drive for surveillance and desktop computer storage. High performance budget storage drive.',
  'Consistent',
  8999.00,
  11999.00,
  'in_stock',
  'active'::product_lifecycle_status,
  '2 Years',
  'Storage',
  'https://fbcsagupcxheyiusjfak.supabase.co/storage/v1/object/public/images/products/placeholder-storage.webp',
  ARRAY['https://fbcsagupcxheyiusjfak.supabase.co/storage/v1/object/public/images/products/placeholder-storage.webp'],
  NOW()
);
